### ISSUE TITLE
Java8 support for the following version

### ISSUE THREAD

**Issue by iampkuhz** [hyperledger/web3j#2069]
## Java 8 support
Java 8 is not support when upgrade from [v4.9.8 to v4.10.0](https://github.com/hyperledger/web3j/compare/v4.9.8...v4.10.0#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721)

Since Java8 is still supported until 2030, it would be great for web3j to support Java8.

thanks.

**Comment by kaygorodov** [comment]
I ran into the same issue when trying to compile it in a project that uses JDK 11. Since the current web3j jar binaries are targeting JDK 17:

[sourceCompatibility
](https://github.com/hyperledger/web3j/blob/main/gradle/java/build.gradle#L3)

, the minimum version of the project where web3j could be used is 17. It would be good to at least document clearly, that the minimum JDK version to use the project is 17

**Comment by gtebrean** [comment]
We won't release a new Web3j version with Java 8 because we are using Hyperledger Besu to run out integration tests and a lower Java version than one used by Besu will result in incompatibilities errors.
